"""API contract dataclasses for the Scrubin backend.

All contracts are *immutable* (``@dataclass(frozen=True)``) and contain
no mutable default values.  They serve as the sole interface between a
frontend client and the deterministic Scrubin Core simulation engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Tuple, Optional

from scrubin.world.state import WorldState
from scrubin.core.events import TimelineEvent

# ---------------------------------------------------------------------------
# Request contracts
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SimulationCreateRequest:
    """Request to create a new simulation session.

    Attributes
    ----------
    seed: int
        Random‑seed for the deterministic ``SimulationRNG`` used by the core.
    initial_tick: int, optional
        Starting tick for the world (default 0).
    """

    seed: int
    initial_tick: int = 0


@dataclass(frozen=True)
class SimulationCreateResponse:
    """Response after a session has been created.

    Attributes
    ----------
    session_id: str
        Unique identifier for the session (opaque to the client).
    initial_world_state: WorldState
        The immutable world snapshot at session start (serialized by the
        transport layer).
    """

    session_id: str
    initial_world_state: WorldState


@dataclass(frozen=True)
class SimulationActionRequest:
    """Request to perform a deterministic action on a session.

    Attributes
    ----------
    session_id: str
        Identifier of the target session.
    action_type: str
        High‑level action name (e.g. ``"perform_procedure"``).
    parameters: Mapping[str, Any]
        Action‑specific parameters – must be JSON‑serialisable.
    timestamp: int
        Logical simulation tick at which the action is issued.
    """

    session_id: str
    action_type: str
    parameters: Mapping[str, Any] = field(default_factory=dict)
    timestamp: int = 0


# ---------------------------------------------------------------------------
# Response contracts
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SimulationActionResponse:
    """Response after an action has been applied.

    Attributes
    ----------
    world_tick: int
        Tick of the resulting world state.
    timeline_events: Tuple[TimelineEvent, ...]
        Events generated by the action.
    updated_score: float
        Placeholder for any scoring metric (e.g., safety score).
    updated_world_state: WorldState
        The new immutable world snapshot.
    active_goals: Tuple[Any, ...]
        Snapshot of active goals (opaque, client‑side can inspect).
    active_intents: Tuple[Any, ...]
        Snapshot of active intents.
    reflection_summary: Any
        Deterministic summary of the reflection stage (opaque).
    learning_summary: Any
        Deterministic summary of the learning stage (opaque).
    """

    world_tick: int
    timeline_events: Tuple[TimelineEvent, ...]
    updated_score: float
    updated_world_state: WorldState
    active_goals: Tuple[Any, ...]
    active_intents: Tuple[Any, ...]
    reflection_summary: Any
    learning_summary: Any


@dataclass(frozen=True)
class SimulationStateResponse:
    """Response containing the current state of a session without mutation.

    Attributes
    ----------
    world_tick: int
    timeline_events: Tuple[TimelineEvent, ...]
    updated_score: float
    current_world_state: WorldState
    active_goals: Tuple[Any, ...]
    active_intents: Tuple[Any, ...]
    reflection_summary: Any
    learning_summary: Any
    """

    world_tick: int
    timeline_events: Tuple[TimelineEvent, ...]
    updated_score: float
    current_world_state: WorldState
    active_goals: Tuple[Any, ...]
    active_intents: Tuple[Any, ...]
    reflection_summary: Any
    learning_summary: Any
