"""Reduced cognition pipeline for benchmark mode.

In benchmark mode the cognition stack is deliberately lightweight:
* No reflection, knowledge‑graph, counterfactual, meta‑pattern, self‑improvement.
* Only the minimal steps required to keep the execution deterministic are run.

The function signature matches the full ``run_cognitive_pipeline`` but performs a
no‑op (or a minimal placeholder) to keep the pipeline fast while preserving the
expected API contract.
"""

from __future__ import annotations

from typing import List

# Import the types that the full pipeline expects – they are passed through
# unchanged but not used.
from scrubin.cognition.executive_policy_decision import ExecutivePolicyDecision


def run_cognitive_pipeline_fast(
    world,  # SimulationWorld – ignored in fast mode
    memory_store,  # MemoryStore – ignored
    fact_store,  # FactStore – ignored
    belief_store,  # BeliefStore – ignored
    reflection_store,  # ReflectionStore – ignored
    graph_store,  # GraphStore – ignored
    counterfactual_store,  # CounterfactualStore – ignored
    meta_store,  # MetaStore – ignored
    plan_store,  # PlanStore – ignored
    executive_store,  # ExecutiveStore – ignored
) -> List[ExecutivePolicyDecision]:
    """Execute a minimal cognition pass.

    Returns an empty list of policy decisions – the benchmark policies (monitor,
    wait, etc.) are generated by the RL env and do not depend on executive
    decisions. The placeholder satisfies the type contract without incurring any
    computational cost.
    """
    # No‑op – deliberately empty to keep benchmark ticks fast.
    return []
