"""Intentive cognition state and autonomous intent definitions.

This module provides deterministic, immutable data structures for the
synthetic autonomous intent layer that operates alongside the existing
semantic intent graph.  All objects are frozen dataclasses and expose
``with_*`` helpers for functional updates.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Tuple, Optional


# ---------------------------------------------------------------------------
# Autonomous intent – a lightweight representation used by the synthesis engine.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AutonomousIntent:
    """Immutable autonomous intent generated by the synthesis engine.

    * ``intent_id`` – unique identifier for the intent.
    * ``description`` – human‑readable description.
    * ``urgency`` – deterministic priority level in ``[0.0, 1.0]``.
    * ``confidence`` – deterministic confidence score in ``[0.0, 1.0]``.
    """

    intent_id: str
    description: str
    urgency: float = 0.0
    confidence: float = 0.0

    def with_urgency(self, urgency: float) -> "AutonomousIntent":
        """Return a copy with ``urgency`` clamped to ``[0.0, 1.0]``."""
        return replace(self, urgency=max(0.0, min(1.0, urgency)))

    def with_confidence(self, confidence: float) -> "AutonomousIntent":
        """Return a copy with ``confidence`` clamped to ``[0.0, 1.0]``."""
        return replace(self, confidence=max(0.0, min(1.0, confidence)))


# ---------------------------------------------------------------------------
# Intentive cognition state – container for all autonomous intents.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class IntentiveCognitionState:
    """Deterministic container for synthesized autonomous intents.

    * ``intents`` – tuple of :class:`AutonomousIntent` objects, ordered by
      ``intent_id`` for deterministic iteration.
    * ``dominant_intent_id`` – identifier of the intent selected as dominant
      based on ``urgency`` → ``confidence`` → lexical order.
    """

    intents: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    dominant_intent_id: Optional[str] = None

    # ---------------------------------------------------------------------
    # Helper mutation methods – each returns a new immutable instance.
    # ---------------------------------------------------------------------
    def add_intent(self, intent: AutonomousIntent) -> "IntentiveCognitionState":
        """Add ``intent`` if its ``intent_id`` is not already present.

        The resulting tuple is kept sorted by ``intent_id`` to guarantee a
        deterministic ordering.
        """
        if any(i.intent_id == intent.intent_id for i in self.intents):
            return self
        new_intents = tuple(sorted(self.intents + (intent,), key=lambda x: x.intent_id))
        return replace(self, intents=new_intents)

    def compute_dominant_intent(self) -> "IntentiveCognitionState":
        """Select the dominant intent deterministically.

        Ordering criteria (in priority order):
        1. Highest ``urgency`` (descending).
        2. Highest ``confidence`` (descending).
        3. Lexicographically smallest ``intent_id``.
        """
        if not self.intents:
            return replace(self, dominant_intent_id=None)
        # Sort according to the criteria described above.
        sorted_intents = sorted(
            self.intents,
            key=lambda i: (-i.urgency, -i.confidence, i.intent_id),
        )
        dominant = sorted_intents[0]
        return replace(self, dominant_intent_id=dominant.intent_id)

    # ``with_*`` style helper – replace the entire intents tuple.
    def with_intents(self, intents: Tuple[AutonomousIntent, ...]) -> "IntentiveCognitionState":
        return replace(self, intents=tuple(sorted(intents, key=lambda x: x.intent_id)))
