'''Intentive cognition state and autonomous intent definitions.

This module provides deterministic, immutable data structures for the
synthetic autonomous intent layer that operates alongside the existing
semantic intent graph.  All objects are frozen dataclasses and expose
``with_*`` helpers for functional updates.
'''

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Tuple, Optional

# Autonomous intent – a lightweight representation used by the synthesis engine.

@dataclass(frozen=True)
class AutonomousIntent:
    '''Immutable autonomous intent generated by the synthesis engine.

    The fields follow the Phase O.7.1 specification.  All tuple collections are
    stored sorted to guarantee deterministic ordering.  ``with_*`` helpers
    return new copies with values clamped where appropriate.
    '''

    # Core identifier – renamed to ``id`` but ``intent_id`` is provided as an alias.
    id: str
    description: str
    originating_goal: Optional[str] = None
    semantic_tags: Tuple[str, ...] = field(default_factory=tuple)
    required_concepts: Tuple[str, ...] = field(default_factory=tuple)
    anticipated_risks: Tuple[str, ...] = field(default_factory=tuple)
    confidence: float = 0.0
    urgency: float = 0.0
    strategic_priority: float = 0.0
    execution_cost: float = 0.0
    uncertainty: float = 0.0
    blocking_conditions: Tuple[str, ...] = field(default_factory=tuple)
    fallback_intents: Tuple[str, ...] = field(default_factory=tuple)
    creation_tick: int = 0
    expiration_tick: Optional[int] = None
    completion_state: str = "pending"

    @property
    def intent_id(self) -> str:
        return self.id

    def with_id(self, new_id: str) -> 'AutonomousIntent':
        return replace(self, id=new_id)

    def with_description(self, desc: str) -> 'AutonomousIntent':
        return replace(self, description=desc)

    def with_originating_goal(self, goal: Optional[str]) -> 'AutonomousIntent':
        return replace(self, originating_goal=goal)

    def with_semantic_tags(self, tags: Tuple[str, ...]) -> 'AutonomousIntent':
        return replace(self, semantic_tags=tuple(sorted(tags)))

    def with_required_concepts(self, concepts: Tuple[str, ...]) -> 'AutonomousIntent':
        return replace(self, required_concepts=tuple(sorted(concepts)))

    def with_anticipated_risks(self, risks: Tuple[str, ...]) -> 'AutonomousIntent':
        return replace(self, anticipated_risks=tuple(sorted(risks)))

    def with_confidence(self, confidence: float) -> 'AutonomousIntent':
        return replace(self, confidence=max(0.0, min(1.0, confidence)))

    def with_urgency(self, urgency: float) -> 'AutonomousIntent':
        return replace(self, urgency=max(0.0, min(1.0, urgency)))

    def with_strategic_priority(self, priority: float) -> 'AutonomousIntent':
        return replace(self, strategic_priority=priority)

    def with_execution_cost(self, cost: float) -> 'AutonomousIntent':
        return replace(self, execution_cost=cost)

    def with_uncertainty(self, uncertainty: float) -> 'AutonomousIntent':
        return replace(self, uncertainty=uncertainty)

    def with_blocking_conditions(self, conditions: Tuple[str, ...]) -> 'AutonomousIntent':
        return replace(self, blocking_conditions=tuple(sorted(conditions)))

    def with_fallback_intents(self, fallbacks: Tuple[str, ...]) -> 'AutonomousIntent':
        return replace(self, fallback_intents=tuple(sorted(fallbacks)))

    def with_creation_tick(self, tick: int) -> 'AutonomousIntent':
        return replace(self, creation_tick=tick)

    def with_expiration_tick(self, tick: Optional[int]) -> 'AutonomousIntent':
        return replace(self, expiration_tick=tick)

    def with_completion_state(self, state: str) -> 'AutonomousIntent':
        return replace(self, completion_state=state)

# Intentive cognition state – container for all autonomous intents.

@dataclass(frozen=True)
class IntentiveCognitionState:
    '''Deterministic container for synthesized autonomous intents.

    * ``active_intents`` – currently actionable intents.
    * ``suppressed_intents`` – intents temporarily disabled.
    * ``completed_intents`` – intents that have finished successfully.
    * ``abandoned_intents`` – intents that were dropped.
    * ``intent_history`` – chronological record of all intents ever seen.
    * ``dominant_intent`` – the intent selected as dominant based on the
      ordering rules (urgency → confidence → id).
    * ``cognitive_tick`` – tick counter for the cognition subsystem.
    '''

    active_intents: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    suppressed_intents: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    completed_intents: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    abandoned_intents: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    intent_history: Tuple[AutonomousIntent, ...] = field(default_factory=tuple)
    dominant_intent: Optional[AutonomousIntent] = None
    cognitive_tick: int = 0

    @property
    def intents(self) -> Tuple[AutonomousIntent, ...]:
        '''Legacy alias for ``active_intents`` used by older code.'''
        return self.active_intents

    @property
    def dominant_intent_id(self) -> Optional[str]:
        return self.dominant_intent.id if self.dominant_intent else None

    def _unique_intent(self, intent: AutonomousIntent, collection: Tuple[AutonomousIntent, ...]) -> bool:
        return not any(i.id == intent.id for i in collection)

    def add_intent(self, intent: AutonomousIntent) -> 'IntentiveCognitionState':
        '''Add ``intent`` to ``active_intents`` and ``intent_history`` if not present.

        Duplicates across all collections are ignored. The resulting tuples are
        kept sorted by ``id`` for deterministic iteration.
        '''
        if not self._unique_intent(intent, self.active_intents):
            return self
        new_active = tuple(sorted(self.active_intents + (intent,), key=lambda x: x.id))
        new_history = tuple(sorted(self.intent_history + (intent,), key=lambda x: x.id))
        return replace(self, active_intents=new_active, intent_history=new_history)

    def suppress_intent(self, intent_id: str) -> 'IntentiveCognitionState':
        '''Move an active intent to ``suppressed_intents`` (no‑op if missing).'''
        intent = next((i for i in self.active_intents if i.id == intent_id), None)
        if not intent:
            return self
        new_active = tuple(i for i in self.active_intents if i.id != intent_id)
        new_suppressed = tuple(sorted(self.suppressed_intents + (intent,), key=lambda x: x.id))
        return replace(self, active_intents=new_active, suppressed_intents=new_suppressed)

    def complete_intent(self, intent_id: str) -> 'IntentiveCognitionState':
        '''Move an active intent to ``completed_intents`` (no‑op if missing).'''
        intent = next((i for i in self.active_intents if i.id == intent_id), None)
        if not intent:
            return self
        new_active = tuple(i for i in self.active_intents if i.id != intent_id)
        new_completed = tuple(sorted(self.completed_intents + (intent,), key=lambda x: x.id))
        return replace(self, active_intents=new_active, completed_intents=new_completed)

    def abandon_intent(self, intent_id: str) -> 'IntentiveCognitionState':
        '''Move an active intent to ``abandoned_intents`` (no‑op if missing).'''
        intent = next((i for i in self.active_intents if i.id == intent_id), None)
        if not intent:
            return self
        new_active = tuple(i for i in self.active_intents if i.id != intent_id)
        new_abandoned = tuple(sorted(self.abandoned_intents + (intent,), key=lambda x: x.id))
        return replace(self, active_intents=new_active, abandoned_intents=new_abandoned)

    def compute_dominant_intent(self) -> 'IntentiveCognitionState':
        '''Select the dominant intent deterministically from ``active_intents``.

        Ordering criteria (in priority order):
        1. Highest ``urgency`` (descending)
        2. Highest ``confidence`` (descending)
        3. Lexicographically smallest ``id``
        '''
        if not self.active_intents:
            return replace(self, dominant_intent=None)
        sorted_intents = sorted(
            self.active_intents,
            key=lambda i: (-i.urgency, -i.confidence, i.id),
        )
        dominant = sorted_intents[0]
        return replace(self, dominant_intent=dominant)

    def with_dominant_intent(self, dominant: Optional[AutonomousIntent]) -> 'IntentiveCognitionState':
        return replace(self, dominant_intent=dominant)

    def with_cognitive_tick(self, tick: int) -> 'IntentiveCognitionState':
        return replace(self, cognitive_tick=tick)

    def with_intents(self, intents: Tuple[AutonomousIntent, ...]) -> 'IntentiveCognitionState':
        '''Replace active intents (legacy). Also updates history.'''
        new_active = tuple(sorted(intents, key=lambda x: x.id))
        new_history = tuple(sorted(self.intent_history + intents, key=lambda x: x.id))
        return replace(self, active_intents=new_active, intent_history=new_history)
