"""Deterministic reflection engine – builds introspective records each tick.

The engine observes the world state and timeline events generated by earlier
engines (GoalManagement, Arbitration, Intent synthesis, etc.) and creates a
``DecisionReflection`` entry that captures the rationale behind decisions.
All updates are functional and replay‑safe.
"""

from __future__ import annotations

from dataclasses import replace
from typing import List

from scrubin.core.events import TimelineEvent
from scrubin.world.state import WorldState
from scrubin.cognition.reflection_state import ReflectionState, DecisionReflection


class ReflectionEngine:
    """Pure engine that records deterministic reflections of the cognition cycle."""

    def __init__(self, rng):
        # ``rng`` retained for API compatibility – not used.
        self.rng = rng

    def evolve(self, world: WorldState) -> WorldState:
        # Retrieve sub‑states (use defaults if missing)
        reflection_state: ReflectionState = getattr(world, "reflection_state", ReflectionState())
        goal_state = getattr(world, "goal_hierarchy_state", None)
        intent_state = getattr(world, "intentive_cognition_state", None)
        conflict_state = getattr(world, "goal_conflict_state", None)

        # Extract events from the current tick that are relevant for reflection
        current_events = [e for e in world.timeline if e.tick == world.tick]
        event_descs = [e.description for e in current_events]

        # Detect signals
        conflict_resolved = [d for d in event_descs if d.startswith("conflict_resolved:")]
        goal_suppressed = [d for d in event_descs if d.startswith("goal_suppressed:")]
        dominant_goal_shift = [d for d in event_descs if d.startswith("dominant_goal_shifted:")]
        dominant_intent_shift = [d for d in event_descs if d.startswith("dominant_intent_shifted:")]
        goal_arbitrated = [d for d in event_descs if d.startswith("goal_arbitrated:")]

        # Determine outcome and tags
        if conflict_resolved or goal_suppressed:
            outcome = "arbitrated"
        else:
            outcome = "success"
        reason_tags = []
        if conflict_resolved:
            reason_tags.append("conflict")
        if goal_suppressed:
            reason_tags.append("suppressed")
        if goal_arbitrated:
            reason_tags.append("arbitrated")
        if dominant_goal_shift:
            reason_tags.append("goal_shift")
        if dominant_intent_shift:
            reason_tags.append("intent_shift")
        reason_tags = tuple(sorted(set(reason_tags)))

        # Extract identifiers for the reflection
        goal_id = goal_state.dominant_goal.id if goal_state and goal_state.dominant_goal else None
        intent_id = intent_state.dominant_intent.id if intent_state and intent_state.dominant_intent else None
        conflict_id = None
        if conflict_resolved:
            # pick first resolved conflict id
            conflict_id = conflict_resolved[0].split(":", 1)[1]

        # Deterministic stability score – success gets 1.0, arbitrated gets 0.5
        stability_score = 1.0 if outcome == "success" else 0.5

        reflection = DecisionReflection(
            id=f"reflect_{world.tick}",
            tick=world.tick,
            goal_id=goal_id,
            intent_id=intent_id,
            conflict_id=conflict_id,
            outcome=outcome,
            reason_tags=reason_tags,
            confidence=1.0,
            stability_score=stability_score,
        )

        # Update reflection state
        reflection_state = reflection_state.add_reflection(reflection)
        # Re‑compute drift / stability indices deterministically
        reflection_state = reflection_state.compute_deterministic_insight()

        # Emit timeline events
        new_events: List[TimelineEvent] = [
            TimelineEvent(tick=world.tick, description=f"reflection_created:{reflection.id}"),
        ]
        # Emit degradation events based on computed indices
        if reflection_state.stability_index < 0.5:
            new_events.append(
                TimelineEvent(tick=world.tick, description="stability_degraded")
            )
        if reflection_state.drift_index > 0.5:
            new_events.append(
                TimelineEvent(tick=world.tick, description="drift_detected")
            )
        # Apply updated reflection state and events to the world
        world = world.with_reflection_state(reflection_state)
        for ev in new_events:
            world = world.append_timeline(ev)
        return world
