"""Phase A (Pre‑Operative Evaluation) DecisionNode definitions.

All nodes use hierarchical IDs of the form
`appendectomy.<phase>.<category>.<action>`.
They are registered in :class:`scrubin.engine.decision_registry.DecisionRegistry`
so that the orchestrator (or an AI agent) can resolve a click to a concrete
``DecisionNode`` and call ``node.execute(world, rng)``.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Imports – keep everything local to the engine package to avoid circular deps.
# ---------------------------------------------------------------------------
from .decision_node import (
    DecisionNode,
    PhysiologicDelta,
    EducationalFeedback,
    OptionMutationRule,
    FailurePropagation,
    ProcedureStateMutation,
    ResourceImpact,
    ExecutionProfile,
    HiddenEffect,
    ComplicationTrigger,
)
from .decision_registry import DecisionRegistry

# ---------------------------------------------------------------------------
# Helper factories for common empty structures
# ---------------------------------------------------------------------------
def _empty_failure() -> FailurePropagation:
    return FailurePropagation(
        latent_failure_score=0.0,
        cumulative_risk_delta=0.0,
        instability_contribution=0.0,
        contamination_contribution=0.0,
        hemorrhage_contribution=0.0,
        cognitive_overload_contribution=0.0,
        delayed_decompensation_ticks=0,
    )

def _noop_procedure_mutation() -> ProcedureStateMutation:
    return ProcedureStateMutation(
        unlock_phases=[],
        block_phases=[],
        advance_phase=False,
        repeat_phase=False,
        force_branch=None,
        terminate_procedure=False,
        require_consult=None,
    )

def _noop_resource_impact() -> ResourceImpact:
    return ResourceImpact()

def _instant_profile() -> ExecutionProfile:
    return ExecutionProfile(
        execution_type="instant",
        duration_seconds=0,
        interruptible=False,
        requires_stability=False,
        requires_visualization=False,
        requires_anesthesia_depth=False,
        requires_assistant=False,
    )

# ---------------------------------------------------------------------------
# A.1 – Initial Patient Assessment – Correct
# ---------------------------------------------------------------------------
node_a1_assess_symptoms = DecisionNode(
    id="appendectomy.a1.assessment.evaluate_symptoms",
    label="Evaluate presenting symptoms",
    canonical_name="evaluate_symptoms",
    category="diagnostic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=10,
    tags=["symptoms", "assessment"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.9,
    board_relevance=0.8,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.95,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[
        HiddenEffect(
            id="hidden.inflammation_detected",
            description="Early inflammatory process recognized – reduces future perforation risk.",
            progression_rate=0.0,
            reveal_threshold=0.0,
            escalation_threshold=0.0,
            affected_systems=["immune"],
            delayed_manifestations=[],
            reversible=True,
            requires_intervention=False,
        )
    ],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=[
            "appendectomy.a1.hemodynamics.evaluate_stability",
            "appendectomy.a1.assessment.characterize_pain",
        ],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Assess Symptoms",
        what_happened="The learner evaluated the patient's reported right‑lower‑quadrant pain, nausea, anorexia and a fever of 38.1 °C.",
        why_it_matters="Correct symptom appraisal raises suspicion for acute appendicitis and early sepsis, guiding timely intervention.",
        anatomical_reasoning="Pain migration and localized tenderness are classic for appendiceal inflammation.",
        physiologic_reasoning="Fever and tachycardia indicate systemic inflammatory response; early recognition allows prompt resuscitation.",
        procedural_reasoning="Accurate symptom assessment defines the diagnostic pathway and prevents downstream delays.",
        future_risk_explanation="Missing these findings would lower diagnostic confidence, increase delay risk and raise the chance of perforation later.",
        recovery_guidance="Continue monitoring vitals and proceed to hemodynamic evaluation.",
        educational_tags=["symptom_assessment", "appendicitis", "early_sepsis"],
        board_style_explanation="Failure to recognize the classic symptom complex delays definitive care and increases morbidity.",
    ),
    score_delta=0.2,
    efficiency_score=0.1,
    safety_score=0.3,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=0.1,
    metadata={"diagnostic_confidence_delta": 0.15, "team_confidence_delta": 0.08, "delay_risk_delta": -0.05},
)
DecisionRegistry.register(node_a1_assess_symptoms)

# ---------------------------------------------------------------------------
# A.1 – Initial Patient Assessment – Incorrect (under‑estimation)
# ---------------------------------------------------------------------------
node_a1_underestimate = DecisionNode(
    id="appendectomy.a1.assessment.observe_without_escalation",
    label="Observe without escalation",
    canonical_name="observe_without_escalation",
    category="diagnostic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=5,
    tags=["symptoms", "missed_tachycardia"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.5,
    board_relevance=0.4,
    realism_weight=0.9,
    correctness="dangerous",
    confidence_score=0.6,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[
        HiddenEffect(
            id="hidden.appendix_perfusion",
            description="Undetected progressive ischemia of the appendix – makes tissue friable later.",
            progression_rate=0.08,
            reveal_threshold=0.0,
            escalation_threshold=0.0,
            affected_systems=["gastrointestinal"],
            delayed_manifestations=["friable_appendix"],
            reversible=False,
            requires_intervention=False,
        )
    ],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=["appendectomy.a1.hemodynamics.evaluate_stability"],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Missed Escalation",
        what_happened="The learner noted tachycardia but dismissed it as pain‑related, providing no further work‑up.",
        why_it_matters="Early systemic signs are harbingers of evolving sepsis; ignoring them reduces diagnostic confidence and raises delay risk.",
        anatomical_reasoning="Appendiceal ischemia is a silent process that can progress to perforation.",
        physiologic_reasoning="Unaddressed tachycardia in the setting of fever reflects compensatory response to hypovolemia/infection.",
        procedural_reasoning="Failing to act now forces the team to manage a more compromised patient later.",
        future_risk_explanation="The hidden perfusion deficit will make the appendix friable, increasing the chance of rupture during dissection.",
        recovery_guidance="Re‑evaluate vitals, consider fluids and early antibiotics.",
        educational_tags=["missed_tachycardia", "sepsis_early"],
        board_style_explanation="Ignoring early warning signs delays definitive care and raises morbidity.",
    ),
    score_delta=-0.3,
    efficiency_score=-0.2,
    safety_score=-0.4,
    tissue_handling_score=-0.2,
    contamination_score=0.0,
    hemodynamic_score=-0.2,
    metadata={"diagnostic_confidence_delta": -0.12, "delay_risk_delta": 0.18},
)
DecisionRegistry.register(node_a1_underestimate)

# ---------------------------------------------------------------------------
# A.1 – Hemodynamic evaluation – Correct
# ---------------------------------------------------------------------------
node_a1_hemo_eval = DecisionNode(
    id="appendectomy.a1.hemodynamics.evaluate_stability",
    label="Evaluate hemodynamic stability",
    canonical_name="evaluate_stability",
    category="hemodynamic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=9,
    tags=["hemodynamics", "stability"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.85,
    board_relevance=0.8,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.93,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=[
            "appendectomy.a1.hemodynamics.begin_fluid_resuscitation",
            "appendectomy.a1.hemodynamics.monitor_lactate",
            "appendectomy.a1.hemodynamics.repeat_vitals",
        ],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Hemodynamic Evaluation",
        what_happened="Learner assessed vitals and identified early compensated hypovolemia and mild systemic inflammatory response.",
        why_it_matters="Early recognition allows timely fluid resuscitation, preventing deterioration during anesthesia.",
        anatomical_reasoning="Third‑spacing of inflammatory fluid shifts intravascular volume.",
        physiologic_reasoning="Tachycardia with borderline BP reflects compensatory catecholamine surge.",
        procedural_reasoning="Stabilizing the patient before induction reduces intra‑operative instability.",
        future_risk_explanation="Delay here would increase the risk of intra‑operative hypotension and organ hypoperfusion.",
        recovery_guidance="Proceed with fluid resuscitation and lactate monitoring.",
        educational_tags=["fluid_resuscitation", "early_hypovolemia"],
        board_style_explanation="Failure to recognize hypovolemia predisposes to peri‑operative shock.",
    ),
    score_delta=0.15,
    efficiency_score=0.1,
    safety_score=0.2,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=0.2,
    metadata={},
)
DecisionRegistry.register(node_a1_hemo_eval)

# ---------------------------------------------------------------------------
# A.1 – Fluid resuscitation – Correct
# ---------------------------------------------------------------------------
node_a1_fluid_resusc = DecisionNode(
    id="appendectomy.a1.hemodynamics.begin_fluid_resuscitation",
    label="Begin fluid resuscitation",
    canonical_name="begin_fluid_resuscitation",
    category="hemodynamic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=8,
    tags=["fluids", "resuscitation"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.9,
    board_relevance=0.85,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.96,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(
        heart_rate=-6,
        systolic_bp=4,
        diastolic_bp=2,
        perfusion=0.07,
    ),
    anatomical_impacts=[],
    hidden_effects=[
        HiddenEffect(
            id="hidden.tissue_hypoxia",
            description="Improved tissue oxygen delivery due to better perfusion.",
            progression_rate=0.0,
            reveal_threshold=0.0,
            escalation_threshold=0.0,
            affected_systems=["tissue"],
            delayed_manifestations=[],
            reversible=True,
            requires_intervention=False,
        )
    ],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=["appendectomy.a1.hemodynamics.monitor_lactate"],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Fluid Resuscitation",
        what_happened="Learner administered crystalloid bolus, decreasing heart rate and raising systolic pressure.",
        why_it_matters="Restoring intravascular volume improves organ perfusion and protects against anesthesia‑induced hypotension.",
        anatomical_reasoning="Replenished circulating volume reduces venous congestion around the inflamed appendix.",
        physiologic_reasoning="Increased preload raises cardiac output, ameliorating tachycardia.",
        procedural_reasoning="A euvolemic patient tolerates pneumoperitoneum and trocar insertion better.",
        future_risk_explanation="Adequate resuscitation reduces future bleeding risk and limits tissue hypoxia.",
        recovery_guidance="Continue monitoring vitals; consider repeat bolus if heart rate remains elevated.",
        educational_tags=["fluid_bolus", "hemodynamic_stability"],
        board_style_explanation="Insufficient fluid resuscitation precipitates intra‑operative shock.",
    ),
    score_delta=0.18,
    efficiency_score=0.12,
    safety_score=0.25,
    tissue_handling_score=0.05,
    contamination_score=0.0,
    hemodynamic_score=0.22,
    metadata={},
)
DecisionRegistry.register(node_a1_fluid_resusc)

# ---------------------------------------------------------------------------
# A.1 – No hemodynamic intervention – Incorrect
# ---------------------------------------------------------------------------
node_a1_no_hemo_intervention = DecisionNode(
    id="appendectomy.a1.hemodynamics.no_intervention",
    label="No hemodynamic intervention",
    canonical_name="no_intervention",
    category="hemodynamic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=4,
    tags=["missed_resuscitation"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.3,
    board_relevance=0.2,
    realism_weight=0.8,
    correctness="dangerous",
    confidence_score=0.45,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[
        HiddenEffect(
            id="hidden.global_perfusion",
            description="Global microvascular stress accumulates due to missed early fluids.",
            progression_rate=0.12,
            reveal_threshold=0.0,
            escalation_threshold=0.0,
            affected_systems=["cardiovascular"],
            delayed_manifestations=["hypotension", "lactate_rise"],
            reversible=False,
            requires_intervention=True,
        ),
        HiddenEffect(
            id="hidden.microvascular_stress",
            description="Subclinical microvascular injury worsens over time.",
            progression_rate=0.08,
            reveal_threshold=0.0,
            escalation_threshold=0.0,
            affected_systems=["microcirculation"],
            delayed_manifestations=[],
            reversible=False,
            requires_intervention=False,
        ),
    ],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=[],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Missed Resuscitation",
        what_happened="Learner chose to observe without giving fluids despite compensated hypovolemia.",
        why_it_matters="The patient’s hidden perfusion deficit will later manifest as hypotension and lactic acidosis during anesthesia.",
        anatomical_reasoning="Fluid shifts remain intravascularly depleted, jeopardising organ perfusion.",
        physiologic_reasoning="Absence of preload augmentation allows tachycardia to persist and may lead to tissue hypoxia.",
        procedural_reasoning="Induction of anesthesia on an under‑resuscitated patient markedly raises the risk of cardiovascular collapse.",
        future_risk_explanation="Later phases will see unstable vitals, increasing bleeding risk and prolonging operative time.",
        recovery_guidance="Re‑assess and consider rapid fluid bolus now.",
        educational_tags=["no_fluids", "latent_hypoperfusion"],
        board_style_explanation="Neglecting early fluid therapy predisposes to peri‑operative shock.",
    ),
    score_delta=-0.35,
    efficiency_score=-0.2,
    safety_score=-0.4,
    tissue_handling_score=-0.1,
    contamination_score=0.0,
    hemodynamic_score=-0.3,
    metadata={},
)
DecisionRegistry.register(node_a1_no_hemo_intervention)

# ---------------------------------------------------------------------------
# A.1 – Pain pattern characterisation – Correct
# ---------------------------------------------------------------------------
node_a1_pain_characterize = DecisionNode(
    id="appendectomy.a1.assessment.characterize_pain",
    label="Characterize pain pattern",
    canonical_name="characterize_pain",
    category="diagnostic",
    phase_id="appendectomy_a1",
    phase_index=0,
    priority=7,
    tags=["pain", "migration"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.88,
    board_relevance=0.8,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.94,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=["appendectomy.a2.diagnostics.order_labs"],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Pain Pattern",
        what_happened="Learner noted the migratory nature of pain from periumbilical to RLQ and the visceral‑parietal transition.",
        why_it_matters="Understanding pain migration is a hallmark of appendiceal inflammation and helps differentiate from other etiologies.",
        anatomical_reasoning="As the inflamed appendix irritates the parietal peritoneum, pain localises to the McBurney point.",
        physiologic_reasoning="Visceral inflammation triggers somatic referral pathways.",
        procedural_reasoning="Accurate pain interpretation narrows the differential and expedites surgical decision‑making.",
        future_risk_explanation="Mis‑classifying pain would increase diagnostic noise and delay operative escalation.",
        recovery_guidance="Proceed to laboratory work‑up to solidify the diagnosis.",
        educational_tags=["pain_migration", "appendicitis"],
        board_style_explanation="Failure to recognize classic pain migration often leads to misdiagnosis.",
    ),
    score_delta=0.2,
    efficiency_score=0.12,
    safety_score=0.15,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=0.05,
    metadata={},
)
DecisionRegistry.register(node_a1_pain_characterize)

# ---------------------------------------------------------------------------
# A.2 – Diagnostic labs – Correct
# ---------------------------------------------------------------------------
node_a2_order_labs = DecisionNode(
    id="appendectomy.a2.diagnostics.order_labs",
    label="Order full laboratory panel",
    canonical_name="order_labs",
    category="diagnostic",
    phase_id="appendectomy_a2",
    phase_index=1,
    priority=9,
    tags=["labs", "CBC", "CMP", "CRP", "lactate"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.9,
    board_relevance=0.85,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.96,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=["appendectomy.a2.imaging.select_modality"],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Order Labs",
        what_happened="Learner ordered CBC, CMP, CRP and lactate, providing objective data on inflammation and metabolic status.",
        why_it_matters="Lab values confirm leukocytosis and elevated inflammatory markers, guiding peri‑operative management.",
        anatomical_reasoning="Systemic inflammation is reflected in blood work.",
        physiologic_reasoning="Elevated lactate signals early tissue hypoperfusion.",
        procedural_reasoning="Having labs helps anticipate intra‑operative instability.",
        future_risk_explanation="Missing these labs could obscure evolving sepsis.",
        recovery_guidance="Review results and integrate with imaging.",
        educational_tags=["CBC", "CRP", "lactate"],
        board_style_explanation="Incomplete labs may lead to under‑recognition of sepsis.",
    ),
    score_delta=0.15,
    efficiency_score=0.1,
    safety_score=0.12,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=0.08,
    metadata={},
)
DecisionRegistry.register(node_a2_order_labs)

# ---------------------------------------------------------------------------
# A.2 – Diagnostic labs – Minimal (incorrect)
# ---------------------------------------------------------------------------
node_a2_minimal_labs = DecisionNode(
    id="appendectomy.a2.diagnostics.minimal_labs",
    label="Order minimal labs (CBC only)",
    canonical_name="minimal_labs",
    category="diagnostic",
    phase_id="appendectomy_a2",
    phase_index=1,
    priority=5,
    tags=["labs", "minimal"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.4,
    board_relevance=0.35,
    realism_weight=0.7,
    correctness="dangerous",
    confidence_score=0.55,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=[],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="Minimal Labs",
        what_happened="Learner limited ordering to CBC only, leaving lactate and CRP unmeasured.",
        why_it_matters="Absent metabolic and inflammatory markers hide early sepsis, reducing diagnostic confidence.",
        anatomical_reasoning="Inflammatory burden cannot be quantified fully.",
        physiologic_reasoning="Undetected lactate elevation may later manifest as unexplained tachycardia.",
        procedural_reasoning="Incomplete data may delay appropriate peri‑operative antibiotics.",
        future_risk_explanation="Hidden sepsis risk remains, increasing intra‑operative instability.",
        recovery_guidance="Order a full panel as soon as possible.",
        educational_tags=["incomplete_labs"],
        board_style_explanation="Insufficient lab work predisposes to missed sepsis.",
    ),
    score_delta=-0.2,
    efficiency_score=-0.1,
    safety_score=-0.15,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=-0.05,
    metadata={},
)
DecisionRegistry.register(node_a2_minimal_labs)

# ---------------------------------------------------------------------------
# A.2 – Imaging selection – Correct (CT with contrast)
# ---------------------------------------------------------------------------
node_a2_ct_select = DecisionNode(
    id="appendectomy.a2.imaging.select_modality",
    label="Select CT abdomen/pelvis with contrast",
    canonical_name="select_ct",
    category="diagnostic",
    phase_id="appendectomy_a2",
    phase_index=1,
    priority=9,
    tags=["imaging", "CT", "contrast"],
    aliases=[],
    hidden=False,
    deprecated=False,
    educational_importance=0.92,
    board_relevance=0.9,
    realism_weight=1.0,
    correctness="correct",
    confidence_score=0.97,
    is_terminal_error=False,
    requires_confirmation=False,
    physiologic_delta=PhysiologicDelta(),
    anatomical_impacts=[],
    hidden_effects=[],
    complication_triggers=[],
    failure_propagation=_empty_failure(),
    procedure_mutation=_noop_procedure_mutation(),
    option_mutation=OptionMutationRule(
        unlock_options=["appendectomy.a2.imaging.interpret_correct"],
        remove_options=[],
        priority_weight_changes={},
        emergency_overrides=[],
        hidden_until_instability=[],
    ),
    resource_impact=_noop_resource_impact(),
    execution_profile=_instant_profile(),
    educational_feedback=EducationalFeedback(
        title="CT Imaging Selection",
        what_happened="Learner chose contrast‑enhanced CT, the gold‑standard modality for appendicitis.",
        why_it_matters="CT provides definitive anatomic detail, identifies perforation, and guides operative planning.",
        anatomical_reasoning="Cross‑sectional imaging visualises appendix size, peri‑appendiceal fat stranding, and free fluid.",
        physiologic_reasoning="Accurate anatomy reduces intra‑operative surprise and limits operative time.",
        procedural_reasoning="Knowing exact appendix location informs trocar placement and dissection strategy.",
        future_risk_explanation="Precise imaging lowers dissection difficulty and bleeding risk.",
        recovery_guidance="Proceed to imaging interpretation.",
        educational_tags=["CT_appendicitis", "contrast"],
        board_style_explanation="Skipping CT can miss occult perforation and increase morbidity.",
    ),
    score_delta=0.22,
    efficiency_score=0.15,
    safety_score=0.25,
    tissue_handling_score=0.0,
    contamination_score=0.0,
    hemodynamic_score=0.05,
    metadata={},
)
DecisionRegistry.register(node_a2_ct_select)
